<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9K58VOG" ignored="0" name="LearningCenterTest" tests="8" failures="1" timestamp="22 五月 2018 13:32:07 GMT" time="104.61" errors="0">
  <testcase name="creditTest" time="8.91" classname="TestCase.LearningCenterTest.Credit"/>
  <testcase name="eddieCorsonMediaTest" time="3.329" classname="TestCase.LearningCenterTest.EddieCorsonMedia"/>
  <testcase name="eddieCorsonReportingHallTest" time="3.05" classname="TestCase.LearningCenterTest.EddieCorsonReportingHall">
    <failure type="java.lang.AssertionError" message="网页标题与预期不符合 expected [爱迪科森网上报告厅] but found [无法找到资源。]">
      <![CDATA[java.lang.AssertionError: 网页标题与预期不符合 expected [爱迪科森网上报告厅] but found [无法找到资源。]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Utils.ActionBot.titleAssert(ActionBot.java:294)
at TestCase.LearningCenterTest.EddieCorsonReportingHall.eddieCorsonReportingHallTest(EddieCorsonReportingHall.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- eddieCorsonReportingHallTest -->
  <testcase name="learningCenterOLTest" time="9.861" classname="TestCase.LearningCenterTest.LearningCenterOL"/>
  <testcase name="moocTest" time="4.894" classname="TestCase.LearningCenterTest.Mooc"/>
  <testcase name="multimediaAccountingVideoTest" time="7.034" classname="TestCase.LearningCenterTest.MultimediaAccountingVideo"/>
  <testcase name="publicAwarenessTest" time="2.431" classname="TestCase.LearningCenterTest.PublicAwareness"/>
  <testcase name="startPointTest" time="9.168" classname="TestCase.LearningCenterTest.StartPoint"/>
</testsuite> <!-- LearningCenterTest -->
